### ISSUE TITLE
Audio write error when sending packets through KISS serial port

### ISSUE THREAD

**Issue by antserran** [wb2osz/direwolf#143] opened 2018-04-26 16:48 UTC
I'm trying to send packets with Direwolf and a KISS application but I get the following error:

Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error retry count exceeded.
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error retry count exceeded.
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error retry count exceeded.
[0L] EB7DZP>GRNSAT:hello
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state
Audio write error: File descriptor in bad state

This is what I got at the beginning:

Audio input device for receive: dsnoop:1,0  (channels 0 & 1)
Audio out device for transmit: dmix:1,0  (channels 0 & 1)
Asked for 44100 samples/sec but got 48000.
for dsnoop:1,0 input.
Channel 0: 1200 baud, AFSK 1200 & 2200 Hz, E+, 48000 sample rate.
Channel 1: 1200 baud, AFSK 1200 & 2200 Hz, E+, 48000 sample rate.
Note: PTT not configured for channel 0. (Ignore this if using VOX.)
Note: PTT not configured for channel 1. (Ignore this if using VOX.)
Ready to accept AGW client application 0 on port 8009 ...
Ready to accept KISS client application on port 8001 ...
Virtual KISS TNC is available on /dev/pts/3
Created symlink /tmp/kisstnc -> /dev/pts/3

The thing is that if I connect my radio to a Ubuntu laptop everything works, the problem comes when I connect the radio to a Debian computer, which might cause the problem.

Any idea?

**Comment by dranch** [comment] 2018-04-30 21:30
Hello.  This Github issue system is for reporting bugs or requesting feature enhancements.  Please close this issue, join the Yahoo support group at direwolf_packet@yahoogroups.com, and re-ask your question there.  Many helpful people will chime in but I bet if you look at the output of "dmesg" at the time of the issue, you'll see USB issues.  Those can be caused by RFI, low-voltage, etc.  Try running your radio in receive-only and see if things run longer.  If they do, you have a good starting point to troubleshoot from.

--David
KI6ZHD

**Closed** 2018-05-02 16:01 UTC
